apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-flask-app-deploy
  template:
    metadata:
      labels:
        app: my-flask-app-deploy
    spec:
      containers:
      - name: my-flask-app-deploy
        image: acrpinpateste.azurecr.io/hello-world:latest
        ports:
        - containerPort: 80