apiVersion: v1
kind: Service
metadata:
  name: my-flask-service-deploy
spec:
  selector:
    app: my-flask-app-deploy
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer